window.Corelane = window.Corelane || {};

Corelane.problems = [
  {
    id: "manual",
    title: "Too Much Manual Work",
    short: "Save time with automation",
    solutionTitle: "Workflow Automation",
    solutionDescription:
      "We design custom systems that remove repetitive tasks so your team can focus on decisions, service, and growth.",
    benefits: [
      "Automate daily operational processes",
      "Connect the tools you already use",
      "Improve hand-offs between teams",
      "Produce consistent operational reports",
    ],
  },
  {
    id: "customers",
    title: "Not Getting Enough Customers",
    short: "Grow with digital channels",
    solutionTitle: "Digital Presence & Acquisition",
    solutionDescription:
      "We help you present a clearer offer online and build the web and application surfaces customers actually use.",
    benefits: [
      "Professional website and web applications",
      "Clearer service and product journeys",
      "Integration with CRM or lead capture tools",
      "Measurement that supports marketing decisions",
    ],
  },
  {
    id: "excel",
    title: "Managing Everything in Excel",
    short: "Move to a real system",
    solutionTitle: "Custom Operations Software",
    solutionDescription:
      "Spreadsheets break as soon as more people, more SKUs, or more rules appear. We replace fragile files with software that matches how you work.",
    benefits: [
      "Shared, permissioned data instead of email attachments",
      "Validation that reduces errors",
      "History and auditability",
      "Room to scale without a rewrite every quarter",
    ],
  },
  {
    id: "inventory",
    title: "Inventory and Order Problems",
    short: "Track and manage in real time",
    solutionTitle: "Inventory & Order Systems",
    solutionDescription:
      "We build or integrate order, stock, and fulfillment flows so operations can see what is available and what is overdue.",
    benefits: [
      "Live stock and order status",
      "Fewer duplicate or missed orders",
      "Integrations with sales channels where needed",
      "Reporting for purchasing and fulfillment",
    ],
  },
  {
    id: "presence",
    title: "Poor Online Presence",
    short: "Professional website and branding",
    solutionTitle: "Web Experience Engineering",
    solutionDescription:
      "We design and develop sites and applications that explain your offer clearly and work reliably on every device.",
    benefits: [
      "Modern, accessible interface",
      "Content structure that supports SEO",
      "Fast, maintainable front end",
      "A foundation you can extend later",
    ],
  },
  {
    id: "social",
    title: "Social Media Is Not Working",
    short: "Structured social programs",
    solutionTitle: "Social Media Management",
    solutionDescription:
      "We plan and operate social programs that support your brand with consistent publishing, not random posts.",
    benefits: [
      "Clear content cadence",
      "Channel-appropriate creative direction",
      "Alignment with your website and offers",
      "Simple reporting on activity and engagement",
    ],
  },
  {
    id: "reports",
    title: "No Clear Reports",
    short: "Dashboards and analytics",
    solutionTitle: "Data Analytics & Reporting",
    solutionDescription:
      "We connect sources, model the data that matters, and present it in dashboards your managers can actually use.",
    benefits: [
      "Defined metrics instead of ad-hoc exports",
      "Scheduled or live reporting",
      "Role-appropriate views",
      "A path from raw data to decisions",
    ],
  },
  {
    id: "legacy",
    title: "Old or Existing Software Issues",
    short: "Modernize and integrate",
    solutionTitle: "Modernization & Integration",
    solutionDescription:
      "We stabilize, wrap, or replace aging systems and connect them through APIs so you are not trapped in a dead end.",
    benefits: [
      "Honest assessment of keep, wrap, or replace",
      "API integrations with current tools",
      "Phased delivery that protects operations",
      "Documentation and handover",
    ],
  },
];

Corelane.services = [
  {
    id: "software",
    title: "Software Development",
    description: "Custom software for workflows, roles, and data that no longer fit a spreadsheet or generic package.",
    href: "/pages/software-development.html",
    image: "/images/opt/svc-software.jpg",
    imageAlt: "Hands at a workstation. Screen content is not a client product.",
  },
  {
    id: "webapps",
    title: "Web Application Development",
    description: "Web applications for internal teams, customers, and partners, with roles and integrations.",
    href: "/pages/web-applications.html",
    image: "/images/opt/svc-webapps.jpg",
    imageAlt: "Someone using a laptop in a meeting room. Not a named product.",
  },
  {
    id: "mobile",
    title: "Mobile App Development",
    description: "iOS and Android apps when the work belongs on a phone, backed by a real system of record.",
    href: "/pages/mobile-apps.html",
    image: "/images/opt/svc-mobile.jpg",
    imageAlt: "A phone held outdoors with a blurred app screen. Not a shipped client app.",
  },
  {
    id: "cloud",
    title: "Cloud Engineering",
    description: "Cloud architecture, migration, and operations you can explain, observe, and recover.",
    href: "/pages/cloud-engineering.html",
    image: "/images/opt/svc-cloud.jpg",
    imageAlt: "A data-center aisle of server racks. Environmental photo, not a named facility.",
  },
  {
    id: "uiux",
    title: "UI/UX Design",
    description: "Interface design for complex operational software — flows people can actually complete.",
    href: "/pages/ui-ux-design.html",
    image: "/images/opt/svc-uiux.jpg",
    imageAlt: "Desk with sketches and a tablet showing blurred wireframes.",
  },
  {
    id: "automation",
    title: "AI and Automation",
    description: "Automation and applied AI on specific, checkable workloads — with human review where risk is high.",
    href: "/pages/ai-automation.html",
    image: "/images/opt/svc-ai.jpg",
    imageAlt: "An operator at a multi-screen workstation. Illustrative, not a named team.",
  },
  {
    id: "social",
    title: "Social Media Management",
    description: "Publishing cadence and brand presence aligned to your website — not invented reach numbers.",
    href: "/pages/social-media.html",
    image: "/images/opt/svc-social.jpg",
    imageAlt: "A phone on a tripod in a small content studio. No live social metrics shown.",
  },
  {
    id: "consulting",
    title: "IT Consulting",
    description: "Build vs buy, keep/wrap/replace, and architecture advice before you commit to a build.",
    href: "/pages/it-consulting.html",
    image: "/images/opt/svc-consulting.jpg",
    imageAlt: "A person at a glass whiteboard in an office at dusk. Illustrative, not named staff.",
  },
];

Corelane.serviceCatalog = Corelane.services.concat([
  {
    id: "web",
    title: "Web Development",
    description: "Corporate and marketing websites with clear structure, accessibility, and maintainable content.",
    href: "/pages/web-development.html",
    image: "/images/opt/svc-web.jpg",
    imageAlt: "A website layout on dual monitors. Not a live client site.",
  },
  {
    id: "devops",
    title: "DevOps",
    description: "CI/CD, environments, and release paths so shipping software is repeatable.",
    href: "/pages/devops.html",
    image: "/images/opt/svc-devops.jpg",
    imageAlt: "Operations monitors with out-of-focus terminals. Not a client SOC.",
  },
  {
    id: "dataeng",
    title: "Data Engineering",
    description: "Pipelines that move operational data between systems of record, warehouses, and tools.",
    href: "/pages/data-engineering.html",
    image: "/images/opt/svc-dataeng.jpg",
    imageAlt: "Fiber cables in a network closet. Infrastructure atmosphere, not a named site.",
  },
  {
    id: "analytics",
    title: "Data Analytics",
    description: "Dashboards and reporting with agreed metric definitions — not invented historical KPIs.",
    href: "/pages/data-analytics.html",
    image: "/images/opt/svc-analytics.jpg",
    imageAlt: "A wall display with blurred charts. No invented KPIs.",
  },
  {
    id: "api",
    title: "API Integration",
    description: "Documented, monitored connections between the systems you already run.",
    href: "/pages/api-integration.html",
    image: "/images/opt/svc-api.jpg",
    imageAlt: "Ethernet cables into a network switch. Supporting photograph only.",
  },
  {
    id: "bizauto",
    title: "Business Automation",
    description: "Workflow systems that replace repetitive operational work after the process is mapped.",
    href: "/pages/business-automation.html",
    image: "/images/opt/svc-bizauto.jpg",
    imageAlt: "A worker scanning a pallet in a warehouse. Environmental photo, not a named client.",
  },
]);

Corelane.industries = [
  {
    id: "healthcare",
    title: "Healthcare",
    description: "Scheduling, hand-offs, permissioned records, and integrations for healthcare operations.",
    href: "/pages/healthcare.html",
    image: "/images/opt/ind-healthcare.jpg",
    imageAlt: "A quiet hospital corridor. Environmental photo, not a named hospital.",
  },
  {
    id: "ecommerce",
    title: "E-Commerce",
    description: "Catalog, order, stock, and integration systems behind a storefront.",
    href: "/pages/ecommerce.html",
    image: "/images/opt/ind-ecommerce.jpg",
    imageAlt: "Hands packing boxes at a fulfillment table. Not a named warehouse.",
  },
  {
    id: "manufacturing",
    title: "Manufacturing",
    description: "Production, inventory, work orders, and plant-adjacent software.",
    href: "/pages/manufacturing.html",
    image: "/images/opt/ind-manufacturing.jpg",
    imageAlt: "A CNC machine on a factory floor. Not a named plant.",
  },
  {
    id: "realestate",
    title: "Real Estate",
    description: "Listings, enquiries, and internal tools for property operations.",
    href: "/pages/real-estate.html",
    image: "/images/opt/ind-realestate.jpg",
    imageAlt: "An empty apartment interior with city windows. Sample setting, not a listing.",
  },
  {
    id: "education",
    title: "Education",
    description: "Program, learner, and administration systems for education providers.",
    href: "/pages/education.html",
    image: "/images/opt/ind-education.jpg",
    imageAlt: "A sunlit lecture hall with a blank screen. Not a named campus.",
  },
  {
    id: "logistics",
    title: "Logistics",
    description: "Movement, tracking, and partner integration for logistics operations.",
    href: "/pages/logistics.html",
    image: "/images/opt/ind-logistics.jpg",
    imageAlt: "Trucks at a loading dock at dusk. Environmental photo, not a named carrier.",
  },
  {
    id: "proservices",
    title: "Professional Services",
    description: "Delivery, resourcing, and client-operations software for firms that sell expertise.",
    href: "/pages/professional-services.html",
    image: "/images/opt/ind-proservices.jpg",
    imageAlt: "An empty boardroom after hours. Illustrative setting, not a named firm.",
  },
];

Corelane.work = [
  {
    id: "hrm-cms",
    category: "Human resources",
    title: "HRM CMS",
    flag: "Project type",
    cta: "View this work",
    description:
      "Permissioned HR systems for employee records, attendance, leave, and the workflows HR teams run day to day. Not a named employer.",
    href: "/pages/work.html#hrm-cms",
    image: "/images/opt/svc-software.jpg",
    imageAlt: "A workstation used as atmosphere. Not a live HRM screenshot.",
  },
  {
    id: "education-portals",
    category: "Education",
    title: "Education portals",
    flag: "Project type",
    cta: "View this work",
    description:
      "Authenticated portals for programmes, learners, and administration. Not a named campus or enrolment figure.",
    href: "/pages/work.html#education-portals",
    image: "/images/opt/ind-education.jpg",
    imageAlt: "A lecture hall used as atmosphere. Not a named institution.",
  },
  {
    id: "business-websites",
    category: "Web presence",
    title: "Business websites",
    flag: "Project type",
    cta: "View this work",
    description:
      "Corporate and marketing websites with a maintainable content structure. Not a ranking or traffic claim.",
    href: "/pages/work.html#business-websites",
    image: "/images/opt/svc-web.jpg",
    imageAlt: "Monitors showing a website layout. Not a live client site.",
  },
  {
    id: "inventory-management",
    category: "Operations",
    title: "Inventory management",
    flag: "Project type",
    cta: "View this work",
    description:
      "Stock, orders, and warehouse hand-offs in a system of record instead of spreadsheets. Not a named warehouse.",
    href: "/pages/work.html#inventory-management",
    image: "/images/opt/svc-bizauto.jpg",
    imageAlt: "Warehouse scanning used as atmosphere. Not a named client site.",
  },
  {
    id: "social-media",
    category: "Brand and channels",
    title: "Social media management",
    flag: "Project type",
    cta: "View this work",
    description:
      "Publishing programs aligned to the website, with a cadence the team can keep. No invented reach numbers.",
    href: "/pages/work.html#social-media",
    image: "/images/opt/svc-social.jpg",
    imageAlt: "A content-studio phone setup. No live social metrics shown.",
  },
];

Corelane.searchIndex = [
  { title: "Home", href: "/index.html", group: "Pages", blurb: "Custom software, cloud, data, and automation for operational problems.", keywords: "corelane homepage software cloud automation", featured: true },
  { title: "Services", href: "/pages/services.html", group: "Pages", blurb: "Software, cloud, data, automation, design, and consulting.", keywords: "catalog offerings", featured: true },
  { title: "Solutions", href: "/pages/solutions.html", group: "Pages", blurb: "Start with the business problem, then choose software, automation, cloud, data, integration, or social programs.", keywords: "challenges automation integration cloud data workflow social media", featured: true },
  { title: "Industries", href: "/pages/industries.html", group: "Pages", blurb: "Healthcare, commerce, manufacturing, and related operations.", keywords: "sectors", featured: true },
  { title: "Our Work", href: "/pages/work.html", group: "Pages", blurb: "HRM CMS, education portals, business websites, inventory systems, and social programs we have delivered.", keywords: "portfolio hrm cms education inventory website social", featured: true },
  { title: "About", href: "/pages/about.html", group: "Pages", blurb: "Who Corelane Systems is, how we think about technology, and how we work with clients.", keywords: "company engineering principles process partner about", featured: true },
  { title: "Process", href: "/pages/process.html", group: "Pages", blurb: "Discovery through support, in sequence.", keywords: "delivery method steps", featured: false },
  { title: "Blog", href: "/pages/blog.html", group: "Pages", blurb: "Notes on software, operations, and delivery.", keywords: "articles notes writing", featured: true },
  { title: "Contact", href: "/pages/contact.html", group: "Contact", blurb: "Form, email, and WhatsApp.", keywords: "email gmail whatsapp phone talk let's", featured: true },
  { title: "Sitemap", href: "/pages/sitemap.html", group: "Pages", blurb: "Every published page on this site.", keywords: "index map pages", featured: false },
  { title: "Keep, wrap, or replace", href: "/pages/note-keep-wrap-replace.html", group: "Notes", blurb: "When an ageing system should stay, be wrapped, or be retired.", keywords: "legacy rewrite", featured: false },
  { title: "Start from the operation", href: "/pages/note-start-from-the-operation.html", group: "Notes", blurb: "Start from workflow and constraints, not a shopping list.", keywords: "discovery operations", featured: false },
  { title: "Delivery you can explain", href: "/pages/note-visible-delivery.html", group: "Notes", blurb: "Status, rollback, and handover as part of delivery.", keywords: "status handover", featured: false },
    { title: "Inventory Without Spreadsheets", href: "/pages/note-inventory-without-spreadsheets.html", group: "Notes", blurb: "Moving to a real system stops the errors that cost most.", keywords: "inventory spreadsheets operations", featured: false },
    { title: "The Most Important Benefits of a Business Website", href: "/pages/note-website-benefits.html", group: "Notes", blurb: "A website is the one surface your business owns.", keywords: "website benefits control", featured: false },
    { title: "What a Business Website Must Explain First", href: "/pages/note-website-first-screen.html", group: "Notes", blurb: "The first screen has three jobs: name the offer, name the audience, and name the next step.", keywords: "website design ui ux offer", featured: false },
    { title: "A Website Is Not Software", href: "/pages/note-website-not-software.html", group: "Notes", blurb: "A website explains the offer. Software runs the operation.", keywords: "software website comparison", featured: false },
    { title: "Why Your Business Still Needs a Website in 2026", href: "/pages/note-why-your-business-needs-a-website.html", group: "Notes", blurb: "Social media is rented infrastructure. A website is the stable address your business controls.", keywords: "website 2026 social media", featured: false },
    { title: "Custom Software vs Off-the-Shelf: How to Decide", href: "/pages/note-custom-software-vs-off-the-shelf.html", group: "Notes", blurb: "When the fit gap costs more than the build.", keywords: "custom software off the shelf", featured: false },
    { title: "When to Automate a Business Process", href: "/pages/note-when-to-automate.html", group: "Notes", blurb: "The right candidate is repetitive, rule-based, and already working.", keywords: "automation processes", featured: false },
  { title: "Privacy Policy", href: "/pages/privacy.html", group: "Legal", blurb: "How this static site treats information.", keywords: "gdpr cookies", featured: false },
  { title: "Terms of Service", href: "/pages/terms.html", group: "Legal", blurb: "Terms of use for this website.", keywords: "legal terms", featured: false },
  { title: "Software Development", href: "/pages/software-development.html", group: "Services", blurb: "Custom systems built around how the operation actually runs.", keywords: "custom software engineering", featured: true },
  { title: "Web Development", href: "/pages/web-development.html", group: "Services", blurb: "Sites that explain the offer and stay maintainable.", keywords: "website frontend", featured: false },
  { title: "Web Application Development", href: "/pages/web-applications.html", group: "Services", blurb: "Internal and customer-facing applications in the browser.", keywords: "saas portal app", featured: false },
  { title: "Mobile App Development", href: "/pages/mobile-apps.html", group: "Services", blurb: "Mobile surfaces when the work actually happens on a phone.", keywords: "ios android", featured: false },
  { title: "Cloud Engineering", href: "/pages/cloud-engineering.html", group: "Services", blurb: "Infrastructure that can be explained, recovered, and operated.", keywords: "aws azure hosting", featured: false },
  { title: "DevOps", href: "/pages/devops.html", group: "Services", blurb: "Build, test, and release paths that the team can run.", keywords: "ci cd pipeline", featured: false },
  { title: "Data Engineering", href: "/pages/data-engineering.html", group: "Services", blurb: "Pipelines that move operational data where it needs to go.", keywords: "etl warehouse", featured: false },
  { title: "Data Analytics", href: "/pages/data-analytics.html", group: "Services", blurb: "Reporting that supports management decisions.", keywords: "dashboard reports bi", featured: false },
  { title: "Business Automation", href: "/pages/business-automation.html", group: "Services", blurb: "Workflows that replace repetitive operational work.", keywords: "rpa excel manual", featured: false },
  { title: "API Integration", href: "/pages/api-integration.html", group: "Services", blurb: "Reliable connections between systems you already run.", keywords: "rest webhook connect", featured: false },
  { title: "UI/UX Design", href: "/pages/ui-ux-design.html", group: "Services", blurb: "Interfaces that match the job, not a trend deck.", keywords: "design product interface", featured: false },
  { title: "AI and Automation", href: "/pages/ai-automation.html", group: "Services", blurb: "Automation where the work is repetitive and checkable.", keywords: "ai llm machine learning", featured: false },
  { title: "Social Media Management", href: "/pages/social-media.html", group: "Services", blurb: "Publishing that supports the brand with a plan.", keywords: "instagram facebook linkedin", featured: false },
  { title: "IT Consulting", href: "/pages/it-consulting.html", group: "Services", blurb: "Advice before you commit to a build.", keywords: "advisory architecture", featured: false },
  { title: "Healthcare", href: "/pages/healthcare.html", group: "Industries", blurb: "Operational software with careful handling of workflow and data.", keywords: "clinic hospital", featured: false },
  { title: "E-Commerce", href: "/pages/ecommerce.html", group: "Industries", blurb: "Catalog, order, and integration behind a storefront.", keywords: "shop store orders", featured: false },
  { title: "Manufacturing", href: "/pages/manufacturing.html", group: "Industries", blurb: "Production, inventory, and plant-adjacent software.", keywords: "factory plant", featured: false },
  { title: "Education", href: "/pages/education.html", group: "Industries", blurb: "Program, learner, and administration systems.", keywords: "school university", featured: false },
  { title: "Logistics", href: "/pages/logistics.html", group: "Industries", blurb: "Movement, tracking, and partner integration.", keywords: "warehouse shipping", featured: false },
  { title: "Real Estate", href: "/pages/real-estate.html", group: "Industries", blurb: "Listings, operations, and internal tools.", keywords: "property listings", featured: false },
  { title: "Professional Services", href: "/pages/professional-services.html", group: "Industries", blurb: "Delivery, resourcing, and client operations software.", keywords: "firm agency", featured: false },
];

Corelane.prefix = function prefix() {
  const isNested = /\/pages\//.test(window.location.pathname);
  return isNested ? "../" : "";
};
